"""
Contains the definition for inception v1 classification network.
The original definition of inception_v1 comes from:
  https://github.com/tensorflow/models/blob/master/research/slim/nets/inception_v1.py
"""


from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

slim = tf.contrib.slim


"""
The wootz compiler parses the prototxt file to understand the network
structure. It then maps the layers in prototxt to tensorflow slim API
and generates the function "inception_v1".
The function needs to take five input arguments:
-- inputs: the input tensor to the model.
-- num_classes: number of predicted classes. This argument corresponds to the 'num_output' in the
     layer: "Logits/Conv2d_0c_1x1" in prototxt; even though the prototxt fixes the output
     dimension to 1000, the generated function could accept any dimension of the output to faciliate
     transfer learning.
-- is_training: whether is training or not. Some operators such as BatchNorm, Dropout will perform
     differently in training and testing state.
-- reuse: whether or not the network's variables should be reused.
-- scope: variable scope.
The default value for the arguments are set by the compiler. For example, if the
prototxt defines the network name as: "alexnet". Then the default scope should also
be "alexnet".
"""

#####################################################################
####### the function below are generated by the Wootz compiler ######
#####################################################################